---
    - name: stop running instance
      amazon.aws.ec2:
        state: 'stopped'
        region: "{{region}}"
        instance_ids: "{{instance_id}}"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
